import { languageNames } from "./languages";
import { writeFile } from "fs/promises";

const header = `"""A list of all supported languages in Shiki.

This file is automatically generated by Shiki Bundler module.
"""

import typing


class Language(typing.NamedTuple):
    """A language supported by Shiki."""
    name: str
    alias: str


languages: typing.List[Language] = [
`;

const footer = "]\n";

const body = languageNames
  .map(
    (lang) =>
      `    Language(name=${JSON.stringify(lang)}, alias=${JSON.stringify(lang)}),`
  )
  .join("\n");

const result = header + body + "\n" + footer;

await writeFile("./shikilangs.py", result, "utf8");
